project:
  type: website
  output-dir: docs

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Blog
      - text: "My Posts"
        menu:
          - href: posts/python-analysis/index.qmd
            text: Python Analysis
          - href: posts/r-analysis/index.qmd
            text: R Analysis
          - href: posts/bonus-r-python/index.qmd
            text: Bonus Post

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true